### ISSUE TITLE
Determine which are relavant flake8 warnings

### ISSUE THREAD

**Issue by bourque** [spacetelescope/ins-jwst-community-software#17]
As part of the Tier 2 standards, we are requiring projects to be compliant with PEP8.  Automated tools such as [`flake8`](https://flake8.pycqa.org/en/latest/) help identify which lines of code violate PEP8.  However, there are some warnings given by `flake8` that may not be relevant or may be overkill for the needs of INS JWST community software.  In this issue, we can identify which warnings we care about and which we can ignore.

**Comment by bourque** [comment]
Here is a list of warnings that I think we could ignore:

- `W391 blank line at end of file` - While slightly annoying, this seems too trivial to care about, and doesn't necessarily impact the readability of the code.  That being said, it may be easily fixed by an automated tool
- `W293 blank line contains whitespace` - Same as above
- `W292 no newline at end of file` - Same as above
- `W291 trailing whitespace` - Same as above
- `W605 invalid escape sequence` - It seems like a lot of these are dealing with regular expressions within python strings, and `flake8` is not quite understanding that(?), so it's not really a problem
- `E401 multiple imports on one line` - I think this makes sense to do to improve readability sometimes, especially if one is importing many many things from the same module.
- `E123 closing bracket does not match indentation of opening bracket's line` - If a code block with a bracket spans multiple lines, some people prefer to close a bracket at the end of the last line instead of creating a new line just for the closing bracket, and I think that is probably fine from a readability standpoint.
- `E124 closing bracket does not match visual indentation` - Same as above
- `E501 line too long` - Adhering to this rule can really impair the readability of code in many cases.

@shanosborne What are your thoughts on this?

**Comment by bourque** [comment]
It looks like specific errors can be igrnored with:

```
flake8 --ignore E24,W504 path/to/code/
```

**Comment by shanosborne** [comment]
@bourque I agree with the ones you list. 

I would also add:
- `W505 doc line too long` - for the same reason as `E501` above. 

And then I also think there's a case for adding:
- `E502 the backslash is redundant` - While redundant, it doesn't really affect readability.
- `W191 indentation contains tabs`  -  pep8 recommends spaces, but text editors can handle either and it doesn't affect readability.
- `E101 Indentation contains mixed spaces and tabs` - see above

**Comment by bourque** [comment]
@shanosborne Sounds good.  Things can sometimes get weird when there are a mix of tabs and spaces, but I agree that it doesn't really affect readability and as long as the code isn't breaking it is probably not a big deal.

With this, we should be able to see where the various projects stray from PEP8 with:

```
flake8 --ignore E101,E123,E124,E401,E501,E502,W191,W291,W292,W293,W391,W505,W605 path/to/code
```

I will run this and update the text files that we currently have in Box.

**Comment by bourque** [comment]
It doesn't appear that `flake8` has the capability to automatically fix issues, but there does exist other tools such as [`autopep8`](https://github.com/hhatto/autopep8) that do this.
