### ISSUE TITLE
Combine Tier 1 and Tier 2?

### ISSUE THREAD

**Issue by bourque** [spacetelescope/ins-jwst-community-software#25]
Now that the INS JWST community tools have finished implementing Tier 1 and Tier 2 standards (for the most part), should we remove the distinction between the two tiers and just have one list of standards?  The original motivation for splitting things up into two tiers was driven by JWST proposal deadlines, which are not really a factor anymore.

**Comment by BradleySappington** [comment]
@mfixstsci, I like keeping 2 tiers as it has been helping with new projects coming on.  If you're amenable I'll close this issue.

**Comment by mfixstsci** [comment]
Thanks @BradleySappington I think this is a good idea. Keeping the two tiers allows the software teams to make progress without feeling overwhelmed by a long list of items to overcome.

**Comment by bourque** [comment]
I'm glad to hear that that new projects are still using this! I have been referring to these standards a lot as we are building a developer guide here at LASP.
