### ISSUE TITLE
calling `setup.py` directly, as indicated in the Tier 1 standard for package structure, is deprecated

### ISSUE THREAD

**Issue by zacharyburnett** [spacetelescope/ins-jwst-community-software#30]
the guidance in the Tier 1 standard for package structure indicates that packages must be installable by calling `setuptools`'s command line interface (`python setup.py install`, `python setup.py develop`, etc.):
https://github.com/spacetelescope/ins-jwst-community-software/blob/be8d9ed740004588db71c8c71cd8ae18fc830935/tier1_standards/package_structure.md?plain=1#L1-L21

However, running `setup.py` directly as a script is deprecated, and recent versions of `setuptools` (greater than `58`) give the following warning:
```
SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
```
This blog post provides a summary of this deprecation: https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html#summary

Additionally, there is no mention of `pyproject.toml`, which most modern projects use to set up a build environment (PEP 517 / 518). In fact, `pyproject.toml` can store all project metadata not related to C extensions (PEP 621), as well as various other metadata tables for other tools, eliminating the need for `setup.cfg` entirely, and also eliminating the need for `setup.py` in pure-Python projects. In cases where C extensions need to be built, such as in the JWST pipeline code, [a shim `setup.py` file can define extensions and include paths](https://github.com/spacetelescope/jwst/blob/ef886bd0b140d9e4c14b4aceab14d0db809e3bf6/setup.py) alongside [a `pyproject.toml` file that defines project metadata](https://github.com/spacetelescope/jwst/blob/ef886bd0b140d9e4c14b4aceab14d0db809e3bf6/pyproject.toml).

I suggest that we modify this standard to instead indicate something to the effect of
> # Software Must Be Installable with `pip install .`
> ...
> ## Short description
> The command `pip install .` (or `pip install -e .`) will build and install all of the modules in the software repository. In order for this command to work, the software repository must have a `pyproject.toml` file and resemble that of a package structure.
> ...

**Comment by BradleySappington** [comment]
Thanks @zacharyburnett, we were actually just updating the Tier 2 standards.  I took care of this as well.
